# Generated by Django 5.2.5 on 2025-08-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deelnemer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aanhef', models.CharField(blank=True, max_length=5, null=True)),
                ('voornaam', models.CharField(blank=True, max_length=100, null=True)),
                ('tussenvoegsel', models.CharField(blank=True, max_length=50, null=True)),
                ('achternaam', models.CharField(blank=True, max_length=100, null=True)),
                ('bedrijfsnaam', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('geboortedatum', models.DateField(blank=True, null=True)),
                ('telefoonnummer', models.CharField(blank=True, max_length=20, null=True)),
                ('windaId', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Deelnemers',
                'constraints': [models.UniqueConstraint(fields=('voornaam', 'achternaam', 'geboortedatum'), name='unieke_deelnemer_constraint')],
            },
        ),
        migrations.CreateModel(
            name='Cursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursus', models.CharField(blank=True, max_length=200, null=True)),
                ('cursusdatum', models.DateField(blank=True, null=True)),
                ('refresher', models.BooleanField(default=False)),
                ('geldigheid_jaren', models.CharField(blank=True, max_length=50, null=True)),
                ('geldigheid_datum', models.DateField(blank=True, null=True)),
                ('deelnemers', models.ManyToManyField(blank=True, related_name='cursussen', to='backend_app.deelnemer')),
            ],
            options={
                'verbose_name_plural': 'Cursussen',
            },
        ),
    ]
