# Generated by Django 5.2.5 on 2025-08-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursus',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
