# Generated by Django 5.2.5 on 2025-09-01 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_cursus_reminder_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRDeelnemer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField(max_length=100)),
                ('achternaam', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefoonnummer', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QREvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(blank=True, max_length=200, null=True)),
                ('datum', models.DateField(blank=True, null=True)),
                ('locatie', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='deelnemer',
            name='unieke_deelnemer_constraint',
        ),
        migrations.AddConstraint(
            model_name='deelnemer',
            constraint=models.UniqueConstraint(fields=('voornaam', 'tussenvoegsel', 'achternaam', 'geboortedatum'), name='unieke_deelnemer_constraint'),
        ),
        migrations.AddField(
            model_name='qrdeelnemer',
            name='qr_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deelnemers', to='backend_app.qrevent'),
        ),
    ]
