# Generated by Django 5.2.5 on 2025-09-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_qrdeelnemer_qrevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrdeelnemer',
            name='tussenvoegsel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='qrevent',
            constraint=models.UniqueConstraint(fields=('titel', 'datum'), name='unique_qr_event'),
        ),
    ]
