# Generated by Django 5.2.5 on 2025-09-01 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_qrdeelnemer_tussenvoegsel_qrevent_unique_qr_event'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='qrevent',
            name='unique_qr_event',
        ),
        migrations.RemoveField(
            model_name='qrdeelnemer',
            name='tussenvoegsel',
        ),
    ]
